chains:
  ethereum:
    enabled: true
    rpc_env: ALCHEMY_ETH_WSS_URL
    quote_tokens:
      WETH: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
      ETH: "0x0000000000000000000000000000000000000000"
      USDC: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
      USDT: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
    sources:
      - name: uniswap_v2
        enabled: true
        type: uniswap_v2_factory
        factory_address: "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
        event: PairCreated
      - name: uniswap_v3
        enabled: true
        type: uniswap_v3_factory
        factory_address: "0x1F98431c8aD98523631AE4a59f267346ea31F984"
        event: PoolCreated
      - name: sushiswap_v2
        enabled: true
        type: uniswap_v2_factory
        factory_address: "0xC0AEe478e3658e2610c5F7A4A2E1777cE9e4f2Ac"
        event: PairCreated
      - name: uniswap_v4
        enabled: true
        type: uniswap_v4_pool_manager
        pool_manager_address: "0x000000000004444c5dc75cB358380D2e3dE08A90"
        event: Initialize
  base:
    enabled: true
    rpc_env: ALCHEMY_BASE_WSS_URL
    quote_tokens:
      WETH: "0x4200000000000000000000000000000000000006"
      ETH: "0x0000000000000000000000000000000000000000"
      USDC: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
      USDbC: "0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA"
    sources:
      - name: aerodrome
        enabled: true
        type: aerodrome_pool_factory
        factory_address: "0x420DD381b31aEf6683db6B902084cB0FFECe40Da"
        event: PoolCreated
      - name: aerodrome_slipstream
        enabled: true
        type: aerodrome_slipstream_factory
        factory_address: "0x5e7BB104d84c7CB9B682AaC2F3d509f5F406809A"
        event: PoolCreated
      - name: uniswap_v4
        enabled: true
        type: uniswap_v4_pool_manager
        pool_manager_address: "0x498581fF718922c3f8e6A244956aF099B2652b2b"
        event: Initialize
      - name: uniswap_v3
        enabled: true
        type: uniswap_v3_factory
        factory_address: "0x33128a8fC17869897dcE68Ed026d694621f6FDfD"
        event: PoolCreated
  bsc:
    enabled: true
    rpc_env: ALCHEMY_BNB_WSS_URL
    quote_tokens:
      WBNB: "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"
      USDT: "0x55d398326f99059fF775485246999027B3197955"
      USDC: "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d"
      BUSD: "0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56"
    sources:
      - name: pancakeswap_v2
        enabled: true
        type: uniswap_v2_factory
        factory_address: "0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73"
        event: PairCreated
      - name: pancakeswap_v3
        enabled: true
        type: uniswap_v3_factory
        factory_address: "0x0BFbCF9fa4f9C56B0F40a671Ad40E0805A091865"
        event: PoolCreated
      - name: uniswap_v3
        enabled: true
        type: uniswap_v3_factory
        factory_address: "0xdB1d10011AD0Ff90774D0C6Bb92e5C5c8b4461F7"
        event: PoolCreated
